//
//  ImageId.swift
//  UGui
//    画像のIDと文字列を管理するenum
//  Created by Shusuke Unno on 2017/07/11.
//  Copyright © 2017年 Shusuke Unno. All rights reserved.
//

import Foundation

public enum ImageName : String {
    case arrow_d = "arrow_d.png"
    case arrow_l = "arrow_l.png"
    case arrow_r = "arrow_r.png"
    case arrow_u = "arrow_u.png"
    case arrow_up = "arrow_up.png"
    case backup_button = "backup_button.png"
    case backup_check_auto_backup = "backup_check_auto_backup.png"
    case backup_complete_backup = "backup_complete_backup.png"
    case backup_complete_restore = "backup_complete_restore.png"
    case backup_confirm_restore = "backup_confirm_restore.png"
    case backup_confirm_restore1 = "backup_confirm_restore1.png"
    case backup_confirm_restore3 = "backup_confirm_restore3.png"
    case backup_list_backup = "backup_list_backup.png"
    case backup_list_item = "backup_list_item.png"
    case backup_page_backup = "backup_page_backup.png"
    case backup_page_restore = "backup_page_restore.png"
    case backup_restore_button = "backup_restore_button.png"
    case backup_restore_from_file = "backup_restore_from_file.png"
    case backup_restore_succeed = "backup_restore_succeed.png"
    case backup_select_file = "backup_select_file.png"
    case box1 = "box1.png"
    case card = "card.png"
    case cards = "cards.png"
    case checked = "checked.png"
    case checked2 = "checked2.png"
    case checked3 = "checked3.png"
    case checked3_frame = "checked3_frame.png"
    case close = "close.png"
    case copy = "copy.png"
    case debug = "debug.png"
    case edit = "edit.png"
    case export = "export.png"
    case favorites = "favorites.png"
    case favorites2 = "favorites2.png"
    case help_add_book = "help_add_book.png"
    case help_add_button = "help_add_button.png"
    case help_add_buttons = "help_add_buttons.png"
    case help_add_card = "help_add_card.png"
    case help_add_csv_book = "help_add_csv_book.png"
    case help_add_csv_list = "help_add_csv_list.png"
    case help_add_preset_book = "help_add_preset_book.png"
    case help_added_csv = "help_added_csv.png"
    case help_added_preset_book = "help_added_preset_book.png"
    case help_backup_button = "help_backup_button.png"
    case help_book_icon_trash = "help_book_icon_trash.png"
    case help_book_win_edit = "help_book_win_edit.png"
    case help_card_info = "help_card_info.png"
    case help_card_info3 = "help_card_info3.png"
    case help_confirm_add_csv = "help_confirm_add_csv.png"
    case help_confirm_add_preset = "help_confirm_add_preset.png"
    case help_confirm_backup = "help_confirm_backup.png"
    case help_confirm_cleanup = "help_confirm_cleanup.png"
    case help_confirm_restore = "help_confirm_restore.png"
    case help_csv_backup1 = "help_csv_backup1.png"
    case help_csv_backup2 = "help_csv_backup2.png"
    case help_csv_backup3 = "help_csv_backup3.png"
    case help_csv_backup4 = "help_csv_backup4.png"
    case help_csv_backup5 = "help_csv_backup5.png"
    case help_csv_backup6 = "help_csv_backup6.png"
    case help_dlg_edit = "help_dlg_edit.png"
    case help_edit_button = "help_edit_button.png"
    case help_edit_card = "help_edit_card.png"
    case help_edit_cards = "help_edit_cards.png"
    case help_finish_add_csv = "help_finish_add_csv.png"
    case help_finish_add_preset = "help_finish_add_preset.png"
    case help_finish_restore = "help_finish_restore.png"
    case help_icon_in_trash = "help_icon_in_trash.png"
    case help_icon_long_push = "help_icon_long_push.png"
    case help_icons_moved = "help_icons_moved.png"
    case help_move_icons = "help_move_icons.png"
    case help_new_book = "help_new_book.png"
    case help_new_card = "help_new_card.png"
    case help_page_backup = "help_page_backup.png"
    case help_page_backup2 = "help_page_backup2.png"
    case help_preset_list = "help_preset_list.png"
    case help_restore_button = "help_restore_button.png"
    case help_selected_icon_move = "help_selected_icon_move.png"
    case help_setting_button = "help_setting_button.png"
    case help_study_book_list = "help_study_book_list.png"
    case help_study_button = "help_study_button.png"
    case help_study_mode1_1 = "help_study_mode1_1.png"
    case help_study_mode1_2 = "help_study_mode1_2.png"
    case help_study_mode1_3 = "help_study_mode1_3.png"
    case help_study_mode2 = "help_study_mode2.png"
    case help_study_mode2_1 = "help_study_mode2_1.png"
    case help_study_mode2_2 = "help_study_mode2_2.png"
    case help_study_mode2_3 = "help_study_mode2_3.png"
    case help_study_mode2_4 = "help_study_mode2_4.png"
    case help_study_mode3_1 = "help_study_mode3_1.png"
    case help_study_mode3_2 = "help_study_mode3_2.png"
    case help_study_mode3_3 = "help_study_mode3_3.png"
    case help_study_mode4_1 = "help_study_mode4_1.png"
    case help_study_mode4_2 = "help_study_mode4_2.png"
    case help_study_mode4_3 = "help_study_mode4_3.png"
    case help_study_mode4_4 = "help_study_mode4_4.png"
    case help_study_mode4_5 = "help_study_mode4_5.png"
    case help_study_options = "help_study_options.png"
    case help_study_result = "help_study_result.png"
    case help_trash_empty = "help_trash_empty.png"
    case help_trash_empty2 = "help_trash_empty2.png"
    case history = "history.png"
    case icon_move = "icon_move.png"
    case license = "license.png"
    case loupe = "loupe.png"
    case mail = "mail.png"
    case more = "more.png"
    case number_0 = "number_0.png"
    case number_1 = "number_1.png"
    case number_2 = "number_2.png"
    case number_3 = "number_3.png"
    case number_4 = "number_4.png"
    case number_5 = "number_5.png"
    case number_6 = "number_6.png"
    case number_7 = "number_7.png"
    case number_8 = "number_8.png"
    case number_9 = "number_9.png"
    case open = "open.png"
    case play = "play.png"
    case question = "question.png"
    case question2 = "question2.png"
    case random = "random.png"
    case restore = "restore.png"
    case return1 = "return1.png"
    case settings_1 = "settings_1.png"
    case sort = "sort.png"
    case sort2 = "sort2.png"
    case sort_by_alphabet2_asc = "sort_by_alphabet2_asc.png"
    case sort_by_alphabet2_desc = "sort_by_alphabet2_desc.png"
    case sort_by_time_asc = "sort_by_time_asc.png"
    case sort_by_time_desc = "sort_by_time_desc.png"
    case study = "study.png"
    case study_mode1 = "study_mode1.png"
    case study_mode2 = "study_mode2.png"
    case study_mode3 = "study_mode3.png"
    case study_mode4 = "study_mode4.png"
    case text = "text.png"
    case trash = "trash.png"
    case trash2 = "trash2.png"
    case trash3 = "trash3.png"
    case zoom_in = "zoom_in.png"
    case zoom_out = "zoom_out.png"
    
    // ファイルパスを返す
    // 全てのファイルにパスをつけるのが面倒なのでメソッド化した
    func path() -> String{
        return "Resource/image/" + self.rawValue
    }
}
